future: true
lsi: true
pygments: true
permalink: pretty
paginate: 10
paginate_path: /page:num
category_dir : /categories
tag_dir : /tags
exclude: [README.md, LICENSE, netclectic.github.io.sublime-project, netclectic.github.io.sublime-workspace]